# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 111, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 20, 91, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.bn_Rec = QtGui.QPushButton(self.centralwidget)
        self.bn_Rec.setGeometry(QtCore.QRect(670, 20, 92, 28))
        self.bn_Rec.setObjectName(_fromUtf8("bn_Rec"))
        self.rb_dl = QtGui.QRadioButton(self.centralwidget)
        self.rb_dl.setGeometry(QtCore.QRect(40, 140, 112, 21))
        self.rb_dl.setObjectName(_fromUtf8("rb_dl"))
        self.rb_lc = QtGui.QRadioButton(self.centralwidget)
        self.rb_lc.setGeometry(QtCore.QRect(40, 110, 112, 21))
        self.rb_lc.setObjectName(_fromUtf8("rb_lc"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 210, 721, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rb_kdbbs = QtGui.QRadioButton(self.groupBox)
        self.rb_kdbbs.setGeometry(QtCore.QRect(10, 30, 101, 19))
        self.rb_kdbbs.setObjectName(_fromUtf8("rb_kdbbs"))
        self.rb_csdn = QtGui.QRadioButton(self.groupBox)
        self.rb_csdn.setGeometry(QtCore.QRect(250, 30, 71, 16))
        self.rb_csdn.setObjectName(_fromUtf8("rb_csdn"))
        self.rb_iqiyi = QtGui.QRadioButton(self.groupBox)
        self.rb_iqiyi.setGeometry(QtCore.QRect(400, 30, 91, 21))
        self.rb_iqiyi.setObjectName(_fromUtf8("rb_iqiyi"))
        self.rb_le = QtGui.QRadioButton(self.groupBox)
        self.rb_le.setGeometry(QtCore.QRect(330, 30, 71, 21))
        self.rb_le.setObjectName(_fromUtf8("rb_le"))
        self.rb_kdyjs = QtGui.QRadioButton(self.groupBox)
        self.rb_kdyjs.setGeometry(QtCore.QRect(120, 30, 121, 19))
        self.rb_kdyjs.setObjectName(_fromUtf8("rb_kdyjs"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 280, 721, 211))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.bn_denoise = QtGui.QPushButton(self.groupBox_2)
        self.bn_denoise.setGeometry(QtCore.QRect(30, 110, 92, 28))
        self.bn_denoise.setObjectName(_fromUtf8("bn_denoise"))
        self.bn_gray = QtGui.QPushButton(self.groupBox_2)
        self.bn_gray.setGeometry(QtCore.QRect(150, 110, 92, 28))
        self.bn_gray.setObjectName(_fromUtf8("bn_gray"))
        self.bn_bin = QtGui.QPushButton(self.groupBox_2)
        self.bn_bin.setGeometry(QtCore.QRect(260, 110, 92, 28))
        self.bn_bin.setObjectName(_fromUtf8("bn_bin"))
        self.bn_dilate = QtGui.QPushButton(self.groupBox_2)
        self.bn_dilate.setGeometry(QtCore.QRect(370, 110, 92, 28))
        self.bn_dilate.setObjectName(_fromUtf8("bn_dilate"))
        self.bn_erode = QtGui.QPushButton(self.groupBox_2)
        self.bn_erode.setGeometry(QtCore.QRect(490, 110, 92, 28))
        self.bn_erode.setObjectName(_fromUtf8("bn_erode"))
        self.bn_equalizeHist = QtGui.QPushButton(self.groupBox_2)
        self.bn_equalizeHist.setGeometry(QtCore.QRect(600, 110, 91, 28))
        self.bn_equalizeHist.setObjectName(_fromUtf8("bn_equalizeHist"))
        self.bn_medianBlur = QtGui.QPushButton(self.groupBox_2)
        self.bn_medianBlur.setGeometry(QtCore.QRect(30, 150, 92, 28))
        self.bn_medianBlur.setObjectName(_fromUtf8("bn_medianBlur"))
        self.bn_zoom = QtGui.QPushButton(self.groupBox_2)
        self.bn_zoom.setGeometry(QtCore.QRect(150, 150, 92, 28))
        self.bn_zoom.setObjectName(_fromUtf8("bn_zoom"))
        self.bn_divide = QtGui.QPushButton(self.groupBox_2)
        self.bn_divide.setGeometry(QtCore.QRect(260, 150, 92, 28))
        self.bn_divide.setObjectName(_fromUtf8("bn_divide"))
        self.bn_undo = QtGui.QPushButton(self.groupBox_2)
        self.bn_undo.setGeometry(QtCore.QRect(370, 150, 92, 28))
        self.bn_undo.setObjectName(_fromUtf8("bn_undo"))
        self.bn_last = QtGui.QPushButton(self.groupBox_2)
        self.bn_last.setGeometry(QtCore.QRect(490, 150, 92, 28))
        self.bn_last.setObjectName(_fromUtf8("bn_last"))
        self.bn_next = QtGui.QPushButton(self.groupBox_2)
        self.bn_next.setGeometry(QtCore.QRect(600, 150, 92, 28))
        self.bn_next.setObjectName(_fromUtf8("bn_next"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cb_dm = QtGui.QComboBox(self.groupBox_2)
        self.cb_dm.setGeometry(QtCore.QRect(130, 31, 111, 31))
        self.cb_dm.setObjectName(_fromUtf8("cb_dm"))
        self.cb_dm.addItem(_fromUtf8(""))
        self.cb_dm.addItem(_fromUtf8(""))
        self.cb_dm.addItem(_fromUtf8(""))
        self.cb_dm.addItem(_fromUtf8(""))
        self.le_dt = QtGui.QLineEdit(self.groupBox_2)
        self.le_dt.setGeometry(QtCore.QRect(130, 70, 111, 31))
        self.le_dt.setObjectName(_fromUtf8("le_dt"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(270, 40, 71, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lb_current = QtGui.QLabel(self.groupBox_2)
        self.lb_current.setGeometry(QtCore.QRect(350, 40, 61, 51))
        self.lb_current.setText(_fromUtf8(""))
        self.lb_current.setObjectName(_fromUtf8("lb_current"))
        self.lb_tess = QtGui.QLabel(self.groupBox_2)
        self.lb_tess.setGeometry(QtCore.QRect(420, 40, 161, 21))
        self.lb_tess.setObjectName(_fromUtf8("lb_tess"))
        self.lb_vgg = QtGui.QLabel(self.groupBox_2)
        self.lb_vgg.setGeometry(QtCore.QRect(420, 70, 161, 21))
        self.lb_vgg.setObjectName(_fromUtf8("lb_vgg"))
        self.le_label = QtGui.QLineEdit(self.groupBox_2)
        self.le_label.setGeometry(QtCore.QRect(600, 30, 91, 31))
        self.le_label.setObjectName(_fromUtf8("le_label"))
        self.bn_train = QtGui.QPushButton(self.groupBox_2)
        self.bn_train.setGeometry(QtCore.QRect(600, 70, 92, 28))
        self.bn_train.setObjectName(_fromUtf8("bn_train"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 500, 721, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 71, 41))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(310, 40, 51, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.le_name = QtGui.QLineEdit(self.groupBox_3)
        self.le_name.setGeometry(QtCore.QRect(110, 40, 191, 31))
        self.le_name.setObjectName(_fromUtf8("le_name"))
        self.le_pass = QtGui.QLineEdit(self.groupBox_3)
        self.le_pass.setGeometry(QtCore.QRect(370, 40, 211, 31))
        self.le_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.le_pass.setObjectName(_fromUtf8("le_pass"))
        self.bn_login = QtGui.QPushButton(self.groupBox_3)
        self.bn_login.setGeometry(QtCore.QRect(600, 40, 92, 31))
        self.bn_login.setObjectName(_fromUtf8("bn_login"))
        self.le_result = QtGui.QLineEdit(self.centralwidget)
        self.le_result.setGeometry(QtCore.QRect(550, 20, 111, 21))
        self.le_result.setObjectName(_fromUtf8("le_result"))
        self.le_dl = QtGui.QLineEdit(self.centralwidget)
        self.le_dl.setGeometry(QtCore.QRect(160, 140, 601, 21))
        self.le_dl.setObjectName(_fromUtf8("le_dl"))
        self.lb_cap = QtGui.QLabel(self.centralwidget)
        self.lb_cap.setGeometry(QtCore.QRect(150, 10, 281, 81))
        self.lb_cap.setText(_fromUtf8(""))
        self.lb_cap.setObjectName(_fromUtf8("lb_cap"))
        self.le_lc = QtGui.QLineEdit(self.centralwidget)
        self.le_lc.setGeometry(QtCore.QRect(160, 110, 601, 21))
        self.le_lc.setObjectName(_fromUtf8("le_lc"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 50, 91, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cb_engine = QtGui.QComboBox(self.centralwidget)
        self.cb_engine.setGeometry(QtCore.QRect(550, 50, 111, 21))
        self.cb_engine.setObjectName(_fromUtf8("cb_engine"))
        self.cb_engine.addItem(_fromUtf8(""))
        self.cb_engine.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 80, 91, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cb_type = QtGui.QComboBox(self.centralwidget)
        self.cb_type.setGeometry(QtCore.QRect(550, 80, 111, 21))
        self.cb_type.setObjectName(_fromUtf8("cb_type"))
        self.cb_type.addItem(_fromUtf8(""))
        self.cb_type.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 180, 101, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cb_divide_method = QtGui.QComboBox(self.centralwidget)
        self.cb_divide_method.setGeometry(QtCore.QRect(140, 180, 121, 31))
        self.cb_divide_method.setObjectName(_fromUtf8("cb_divide_method"))
        self.cb_divide_method.addItem(_fromUtf8(""))
        self.cb_divide_method.addItem(_fromUtf8(""))
        self.cb_divide_method.addItem(_fromUtf8(""))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(290, 180, 101, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.le_divide_thresh = QtGui.QLineEdit(self.centralwidget)
        self.le_divide_thresh.setGeometry(QtCore.QRect(390, 180, 113, 31))
        self.le_divide_thresh.setObjectName(_fromUtf8("le_divide_thresh"))

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.bn_Rec, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.rec)
        QtCore.QObject.connect(self.rb_kdbbs, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.kdbbs)
        QtCore.QObject.connect(self.rb_csdn, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.csdn)
        QtCore.QObject.connect(self.rb_iqiyi, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.iqiyi)
        QtCore.QObject.connect(self.rb_le, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.le)
        QtCore.QObject.connect(self.rb_lc, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.selectPath)
        QtCore.QObject.connect(self.bn_denoise, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.denoise)
        QtCore.QObject.connect(self.bn_gray, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.gray)
        QtCore.QObject.connect(self.bn_bin, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.bin)
        QtCore.QObject.connect(self.bn_dilate, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.dilate)
        QtCore.QObject.connect(self.bn_erode, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.erode)
        QtCore.QObject.connect(self.bn_equalizeHist, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.equalizeHist)
        QtCore.QObject.connect(self.bn_medianBlur, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.medianBlur)
        QtCore.QObject.connect(self.bn_undo, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.undo)
        QtCore.QObject.connect(self.bn_last, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.last)
        QtCore.QObject.connect(self.bn_next, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.next)
        QtCore.QObject.connect(self.bn_divide, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.divide)
        QtCore.QObject.connect(self.rb_kdyjs, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.kdyjs)
        QtCore.QObject.connect(self.bn_login, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.login)
        QtCore.QObject.connect(self.cb_engine, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), mainWindow.engine)
        QtCore.QObject.connect(self.bn_zoom, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.zoom)
        QtCore.QObject.connect(self.bn_train, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWindow.train)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "验证码识别系统", None))
        self.label.setText(_translate("mainWindow", "图像验证码：", None))
        self.label_2.setText(_translate("mainWindow", "识别结果：", None))
        self.bn_Rec.setText(_translate("mainWindow", "识别", None))
        self.rb_dl.setText(_translate("mainWindow", "下载识别：", None))
        self.rb_lc.setText(_translate("mainWindow", "本地图片：", None))
        self.groupBox.setTitle(_translate("mainWindow", "示例", None))
        self.rb_kdbbs.setText(_translate("mainWindow", "科大bbs", None))
        self.rb_csdn.setText(_translate("mainWindow", "csdn", None))
        self.rb_iqiyi.setText(_translate("mainWindow", "爱奇艺", None))
        self.rb_le.setText(_translate("mainWindow", "乐视", None))
        self.rb_kdyjs.setText(_translate("mainWindow", "科大研究生", None))
        self.groupBox_2.setTitle(_translate("mainWindow", "高级", None))
        self.bn_denoise.setText(_translate("mainWindow", "降噪", None))
        self.bn_gray.setText(_translate("mainWindow", "灰度化", None))
        self.bn_bin.setText(_translate("mainWindow", "二值化", None))
        self.bn_dilate.setText(_translate("mainWindow", "膨胀", None))
        self.bn_erode.setText(_translate("mainWindow", "腐蚀", None))
        self.bn_equalizeHist.setText(_translate("mainWindow", "均衡化", None))
        self.bn_medianBlur.setText(_translate("mainWindow", "中值滤波", None))
        self.bn_zoom.setText(_translate("mainWindow", "放大", None))
        self.bn_divide.setText(_translate("mainWindow", "分割", None))
        self.bn_undo.setText(_translate("mainWindow", "撤销", None))
        self.bn_last.setText(_translate("mainWindow", "上张", None))
        self.bn_next.setText(_translate("mainWindow", "下张", None))
        self.label_3.setText(_translate("mainWindow", "降噪方式：", None))
        self.label_4.setText(_translate("mainWindow", "降噪阈值：", None))
        self.cb_dm.setItemText(0, _translate("mainWindow", "去小点", None))
        self.cb_dm.setItemText(1, _translate("mainWindow", "去多像素", None))
        self.cb_dm.setItemText(2, _translate("mainWindow", "去少像素1", None))
        self.cb_dm.setItemText(3, _translate("mainWindow", "去少像素2", None))
        self.label_9.setText(_translate("mainWindow", "当前字符：", None))
        self.lb_tess.setText(_translate("mainWindow", "tesseract：", None))
        self.lb_vgg.setText(_translate("mainWindow", "vgg：", None))
        self.bn_train.setText(_translate("mainWindow", "训练", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "登录", None))
        self.label_5.setText(_translate("mainWindow", "用户名：", None))
        self.label_8.setText(_translate("mainWindow", "密码：", None))
        self.bn_login.setText(_translate("mainWindow", "登录", None))
        self.label_6.setText(_translate("mainWindow", "识别引擎：", None))
        self.cb_engine.setItemText(0, _translate("mainWindow", "tesseract", None))
        self.cb_engine.setItemText(1, _translate("mainWindow", "vgg", None))
        self.label_7.setText(_translate("mainWindow", "识别类型：", None))
        self.cb_type.setItemText(0, _translate("mainWindow", "数字", None))
        self.cb_type.setItemText(1, _translate("mainWindow", "数字+字母", None))
        self.label_10.setText(_translate("mainWindow", "分割方式：", None))
        self.cb_divide_method.setItemText(0, _translate("mainWindow", "固定长度", None))
        self.cb_divide_method.setItemText(1, _translate("mainWindow", "投影", None))
        self.cb_divide_method.setItemText(2, _translate("mainWindow", "连通域", None))
        self.label_11.setText(_translate("mainWindow", "分割阈值：", None))

